# Generated by Django 5.2.8 on 2025-12-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Сумма оплаты"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Сумма оплаты"
            ),
        ),
    ]
