# Generated by Django 5.2.8 on 2025-12-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_course_amount_lesson_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="Сумма оплаты"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="Сумма оплаты"),
        ),
    ]
