name: Django CI/CD with Docker

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/online-school:latest
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # Остановка старого контейнера (если есть)
            docker rm -f django || true
            # Запуск нового контейнера из Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/online-school:latest
            docker run -d \
              --name django \
              -p 8000:8000 \
              -e DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" \
              -e DEBUG="${{ secrets.DEBUG }}" \
              -e DB_NAME="${{ secrets.DB_NAME }}" \
              -e DB_USER="${{ secrets.DB_USER }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e DB_HOST="${{ secrets.DB_HOST }}" \
              -e DB_PORT="${{ secrets.DB_PORT }}" \
              -e EMAIL_HOST="${{ secrets.EMAIL_HOST }}" \
              -e EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}" \
              -e STRIPE_API_KEY="${{ secrets.STRIPE_API_KEY }}" \
              -e CELERY_BROKER_URL="${{ secrets.CELERY_BROKER_URL }}" \
              -e CELERY_RESULT_BACKEND="${{ secrets.CELERY_RESULT_BACKEND }}" \
              -e REDIS_URL="${{ secrets.REDIS_URL }}" \
              ${{ secrets.DOCKER_USERNAME }}/online-school:latest
